# Generated by Django 5.2.13 on 2026-05-21 18:03

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("coppermind", "0001_initial"),
        ("universe", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CU", "Cultura"),
                            ("EVT", "Eventos y eras"),
                            ("FDV", "Formas de vida"),
                            ("LIB", "Libros"),
                            ("LOC", "Localizaciones"),
                            ("MG", "Magia"),
                            ("PJ", "Personajes"),
                            ("OBJ", "Objetos y materiales"),
                            ("ORG", "Organización"),
                            ("FAM", "Familia"),
                            ("MUL", "Multimedia"),
                            ("WIKI", "Wiki/otros"),
                            ("DIS", "Disambiguación"),
                            ("RD", "Redirección"),
                            ("SUB", "Subpágina"),
                        ],
                        max_length=4,
                        null=True,
                        verbose_name="Tipo de artículo",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Alta"),
                            (2, "Media"),
                            (3, "Baja"),
                            (4, "Subpáginas"),
                            (5, "Siraya"),
                            (99, "TBD"),
                        ],
                        null=True,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("untranslated", "Sin traducir"),
                            ("translating", "Traduciendo"),
                            ("translated", "Traducido"),
                            ("reviewing", "Revisando"),
                            ("reviewed", "Revisado"),
                            ("gregoring", "Engregoriando"),
                            ("gregorio", "Engregoriado"),
                        ],
                        db_index=True,
                        default="untranslated",
                        max_length=16,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "assigned_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha asignación traductor"
                    ),
                ),
                (
                    "translated_at",
                    models.DateField(blank=True, null=True, verbose_name="Fecha traducido"),
                ),
                (
                    "reviewer_assigned_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha asignación revisor"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateField(blank=True, null=True, verbose_name="Fecha revisado"),
                ),
                (
                    "gregorio_assigned_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha asignación gregorio"
                    ),
                ),
                (
                    "gregorio_at",
                    models.DateField(blank=True, null=True, verbose_name="Fecha engregoriado"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "url_drive",
                    models.URLField(blank=True, null=True, verbose_name="URL Drive"),
                ),
                (
                    "linked_copper_en",
                    models.BooleanField(default=False, verbose_name="Enlazada en la Coppermind EN"),
                ),
                (
                    "problem_copper",
                    models.TextField(blank=True, null=True, verbose_name="Problemas de la Copper"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gregorio",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"groups__name": "Admins"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="engregoriados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gregorio",
                    ),
                ),
                (
                    "page_en",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"ns": 0, "wiki": "en"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="article_en",
                        to="coppermind.page",
                        verbose_name="Página EN",
                    ),
                ),
                (
                    "page_es",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"ns": 0, "wiki": "es"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="article_es",
                        to="coppermind.page",
                        verbose_name="Página ES",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"groups__name": "Reviewers"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisor",
                    ),
                ),
                (
                    "translator",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"groups__name": "Translators"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="translations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Traductor",
                    ),
                ),
                (
                    "universe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="articles",
                        to="universe.universe",
                        verbose_name="Universo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artículo",
                "verbose_name_plural": "Artículos",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("page_en__isnull", False),
                            ("page_es__isnull", False),
                            _connector="OR",
                        ),
                        name="article_must_have_at_least_one_page",
                    )
                ],
            },
        ),
    ]
