# Generated by Django 5.2.13 on 2026-05-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wiki",
                    models.CharField(
                        choices=[("en", "Coppermind (EN)"), ("es", "Coppermind (ES)")],
                        db_index=True,
                        max_length=2,
                        verbose_name="Wiki",
                    ),
                ),
                (
                    "page_id",
                    models.PositiveIntegerField(
                        help_text="ID de página en MediaWiki", verbose_name="Page ID"
                    ),
                ),
                ("ns", models.IntegerField(verbose_name="Namespace")),
                ("title", models.CharField(max_length=512, verbose_name="Título")),
                (
                    "touched",
                    models.DateTimeField(
                        help_text="Campo 'touched' de la API de MediaWiki",
                        verbose_name="Última modificación",
                    ),
                ),
                (
                    "fullurl",
                    models.URLField(max_length=1024, verbose_name="URL completa"),
                ),
                (
                    "editurl",
                    models.URLField(max_length=1024, verbose_name="URL de edición"),
                ),
                (
                    "synced_at",
                    models.DateTimeField(auto_now=True, verbose_name="Última sincronización"),
                ),
            ],
            options={
                "verbose_name": "Página",
                "verbose_name_plural": "Páginas",
                "ordering": ["wiki", "ns", "title"],
                "indexes": [
                    models.Index(fields=["wiki", "ns"], name="coppermind__wiki_c6a5a4_idx"),
                    models.Index(fields=["wiki", "title"], name="coppermind__wiki_94233e_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("wiki", "page_id"), name="unique_page_per_wiki")
                ],
            },
        ),
    ]
