# Generated by Django 5.2.13 on 2026-04-16 17:14

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Universe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "universe",
                    models.CharField(max_length=50, unique=True, verbose_name="universo"),
                ),
            ],
            options={
                "verbose_name": "Universo",
                "verbose_name_plural": "Universos",
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("universe"),
                        name="universe_unique",
                    )
                ],
            },
        ),
    ]
